# Generated by Django 4.2.11 on 2024-04-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
