services:

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - store_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  redis:
    image: redis:7.2-alpine
    restart: always


  web:
    build: ../..
    restart: always
    depends_on:
      - db
    volumes:
      - store_static_value:/app/static
    env_file:
      - ./.env

  celery:
    build: ../..
    command: celery worker -A store -l INFO
    restart: always
    depends_on:
      - redis
      - web
    env_file:
      - ./.env


  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - store_static_value:/var/html/static/

volumes:
  store_postgres_data:
  store_static_value:
