# Generated by Django 4.2.11 on 2024-04-23 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0006_rename_descriptiom_products_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
                ('phone_number', models.CharField(default=False, max_length=20, verbose_name='Phone number')),
                ('requires_delivery', models.BooleanField(verbose_name='Delivery')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Delivery address')),
                ('payment_on_get', models.BooleanField(default=False, verbose_name='Pay on get')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Order is paid')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'In processing'), (1, 'On way'), (2, 'Delivered'), (3, 'Received')], default=0, verbose_name='Order status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Order owner')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.products', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Sold item',
                'verbose_name_plural': 'Sold items',
            },
        ),
    ]
