# Generated by Django 4.2.11 on 2024-04-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='product_category',
        ),
    ]
