# Generated by Django 4.2.11 on 2024-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descriptiom',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Discount in %'),
        ),
    ]
